### ISSUE TITLE
Datetime attribute partial not working as expected due to format problems

### ISSUE THREAD

**Issue by LifeIsALesson** [upmin/upmin-admin-ruby#102]
Thanks for building such a great admin framework!

I was not able to get a datetime attribute working as expected. The chosen datepicker (pickaday.js) did an unwanted formatting of the date. The function parseDate(dateString) in https://github.com/upmin/upmin-admin-ruby/blob/master/app/assets/javascripts/upmin/attributes/datetime.js expects a specific format or produces unexpected results otherwise.

Pikaday.js' formatting issue is described in https://github.com/dbushell/Pikaday/issues/71. It is building on moment.js, which has to be imported before pikaday.js to be able to use its formatting features. At the moment pikaday.js gets loaded in upmin's application.js manifest before moment.js gets loaded via upmin's application layout file. A solution is to switch the order of loading the files.

**Comment by MaRoe** [comment]
Unfortunately I ran in this issue today with a current upmin. I have localized dates like dd.mm.yyyy but I get messed up results like: 0010-10-20.

Any ideas for that?
