### ISSUE TITLE
Customize which attributes are shown for instances of any model

### ISSUE THREAD

**Issue by elersong** [upmin/upmin-admin-ruby#141]
I've read through the wiki (really sparse), watched videos (again) and read through the current issues. I have found no current-updated way to select which attributes I want to show for each record on the index page of each model. For instance, on my User model, I only want upmin to give me the User instance's :name, :email, and :number_logins... however, it's currently giving me all of the attributes on that db table. 

How do I customize like that?

**Comment by gabrielrios** [comment]
You can [customize your models](https://github.com/upmin/upmin-admin-ruby/wiki/Customizing-Models)

Or Even [customize your search results](https://www.upmin.com/admin-rails#cust-search-results)

First option would impact into the form too.
