### ISSUE TITLE
Datepicker always only insert the current month in datetime fields

### ISSUE THREAD

**Issue by ameft** [upmin/upmin-admin-ruby#142]
I've just noticed that the datepicker included in upmin has some problems with (only) the month of the picked date: it will indeed always insert the current month in the value of the hidden input field of the date. Day, year and time are correctly picked instead.
It is worth noting that the picked date is correctly displayed to the user in the date field, but that date it's not the same that it's inserted in the hidden field and therefore saved to the database, in which the month is always the current.
I've tried to change the date of my pc with jenuary to confirm that the month inserted is the current.
I'm using the current upmin master.
The problem is only mine? I've tried with Chrome, FF, and IE.

**Comment by joncalhoun** [comment]
Sorry for the delay - this is likely a bug. I'll have to dig into it this week. Not sure how it slipped by. Def need tests for this.

**Comment by ameft** [comment]
Thank you Jon!

**Comment by ameft** [comment]
Any news about the fix of this issue? It's quite important.
Thanks!

**Comment by jdurand** [comment]
Can you still reproduce this?
It's seems to work properly on my end : 
[![Gyazo](http://i.gyazo.com/bd33b5088ec3ab8bf47f9a6551dbb61a.gif)](http://gyazo.com/bd33b5088ec3ab8bf47f9a6551dbb61a)

**Comment by ameft** [comment]
I've updated upmin from the master branch but the problem persists, as you can see the month doesn't change in the hidden input field:

![](http://i.gyazo.com/3ffe97eae8b521eb13a41004574d05f5.gif)

**Comment by jdurand** [comment]
From the look of it, the datetime input has likely never worked before.
This is now fixed.

Yep, Gyazo is pretty neat ;-)

**Comment by ameft** [comment]
Amazing thanks!
