### ISSUE TITLE
The gem I install has differences from the one in github although version is the same

### ISSUE THREAD

**Issue by pedrovasconcelos** [upmin/upmin-admin-ruby#162]
First of all thanks for this great gem!

I don't know if it's just me doing something wrong but the gem I install using bundle install is different from what I find here in github. I'm using upmin-admin 0.1.01

I noticed this because I needed the delete feature for models and couldn't find it. I then noticed that it seems to be implemented in the files shown here in github but not in the version I installed (which is also 0.1.01). Examples of differences:

In "upmin-admin-ruby/app/views/upmin/partials/models/_model.html.haml",
This part is missing from the gem files I have locally (meaning I have no delete button):
```
= link_to(model.path, method: :delete, class: "btn btn-sm btn-danger delete pull-right", title: "Delete #{model.title}.", data: {confirm: "Are you sure?"}) do
      %span.glyphicon.glyphicon-trash.white
```

I also do not have a DELETE route in "upmin-admin-ruby/config/routes.rb"

It's probably something stupid on my part.. I'm kind of new here :) Any ideas?

Thanks in advance!

**Comment by pedrovasconcelos** [comment]
My bad! Just noticed that this feature is planned for release only in version 0.1.1.
Thanks

**Comment by mbrookes** [comment]
The published gem is behind master on Github, but you can use :git in your gemfile to pull from the repository. You might want to target a specific reference so it doesn't change out from under you.

http://bundler.io/git.html

**Comment by pedrovasconcelos** [comment]
I followed your advice and it's working fine now. Many thanks ;)
