### ISSUE TITLE
Ability to delete record is missing

### ISSUE THREAD

**Issue by rizalmuthi** [upmin/upmin-admin-ruby#163]
How do I delete a record on upmin?
I could not find a delete button or should I implement it on model ?

Thanks for clarifying.

**Comment by rizalmuthi** [comment]
After read the PRs and Issues, that I found out its already implemented on this PR

but again, i could not find the delete function and nor the routes
```
Routes for Upmin::Engine:
              root GET      /                                 upmin/models#dashboard
   upmin_dashboard GET      /                                 upmin/models#dashboard
      upmin_search GET|POST /m/:klass(.:format)               upmin/models#search
   upmin_new_model GET      /m/:klass/new(.:format)           upmin/models#new
upmin_create_model POST     /m/:klass/new(.:format)           upmin/models#create
       upmin_model GET      /m/:klass/i/:id(.:format)         upmin/models#show
                   PUT      /m/:klass/i/:id(.:format)         upmin/models#update
      upmin_action POST     /m/:klass/i/:id/:method(.:format) upmin/models#action
```

**Comment by chenwj87** [comment]
+1 I'm having the same issue too. Love it that upmin takes two lines of code to implement. But wondering how to delete

**Comment by mbrookes** [comment]
The published gem is behind master on Github, but you can use :git in your gemfile to pull from the repository. You might want to target a specific reference so it doesn't change out from under you.

http://bundler.io/git.html
