### ISSUE TITLE
Color attribute of model overwritten by upmin

### ISSUE THREAD

**Issue by DriesS** [upmin/upmin-admin-ruby#172]
In my model I have an attribute color but in upmin the value for this field is always light_blue. I think it comes from the configuration class that overwrite my model color value.

https://github.com/upmin/upmin-admin-ruby/blob/master/lib/upmin/configuration.rb#L104

In database everything is saved fine but always displaying wrong value in upmin.

**Comment by mbrookes** [comment]
Dupe of #146
