### ISSUE TITLE
Markdown formatting problem

### ISSUE THREAD

**Issue by joshukraine** [upmin/upmin-admin-ruby#174]
You have a markdown formatting issue in your README. It looks like you're using three apostrophes instead of three backticks. 

![screen shot 2015-05-18 at 8 11 29 am](https://cloud.githubusercontent.com/assets/615841/7674651/9659a27c-fd35-11e4-861b-488e6606b187.png)

**Comment by mbrookes** [comment]
Fixed, thanks,
