### ISSUE TITLE
https://www.upmin.com/admin-rails is a bad link

### ISSUE THREAD

**Issue by ashrocket** [upmin/upmin-admin-ruby#175]

**Comment by joncalhoun** [comment]
upmin.com now forwards to the github repo. all other links are going to continue to fail. If there are some docs that need updated, please submit a PR with updates to those. Thanks!

**Comment by ashrocket** [comment]
Sure, but the very first link in the repo will produce a 404.  Was there a special section you wanted "admin-rails" to point to in the wiki or something?

![screen shot 2015-06-03 at 1 57 37 pm](https://cloud.githubusercontent.com/assets/713675/7967552/baefa954-09f8-11e5-889b-57f3140c205c.png)

**Comment by jdurand** [comment]
I removed it.
Thanks for reporting.
