### ISSUE TITLE
Basic dashboard

### ISSUE THREAD

**Issue by mbrookes** [upmin/upmin-admin-ruby#98]
What MVP level spec did you have in mind for this?

**Comment by SeanLF** [comment]
:+1:

**Comment by SeanLF** [comment]
:+1: Looks good!
Any updates?

**Comment by mbrookes** [comment]
It's pretty much code-complete (albeit with the elimitations mentioned above), but lacking tests. I'm no longer actively involved with upmin-admin, but if you'd like to fork and add some basic tests, I'll gladly merge and push a new gem. Feel free to tweak any code that is lacking or add features you need.

**Comment by mbrookes** [comment]
Merged and released (without tests) with PR #177
